App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
      - Length:
          min: 3
          max: 100
          groups: ['create', 'edit']
    country:
      - NotBlank:
          groups: ['create', 'edit']
      - Length:
          min: 2
          max: 2
          groups: ['create', 'edit']
          minMessage: 'Country code must be exactly 2 characters.'
          maxMessage: 'Country code must be exactly 2 characters.'
    latitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          notInRangeMessage: 'Latitude must be between -90 and 90 degrees.'
          groups: ['create', 'edit']
    longitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -180
          max: 180
          notInRangeMessage: 'Longitude must be between -180 and 180 degrees.'
          groups: ['create', 'edit']

App\Entity\Measurement:
  properties:
    date:
      - NotBlank:
          groups: ['create', 'edit']
      - Date:
          message: 'Please provide a valid date format.'
          groups: ['create', 'edit']
    celsius:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -50
          max: 60
          notInRangeMessage: 'Temperature must be between -50 and 60 degrees Celsius.'
          groups: ['create', 'edit']
    location:
      - NotBlank:
          groups: ['create', 'edit']
